AWSTemplateFormatVersion: '2010-09-09'
Description: This template is to create an EC2 instance,IAM roles with SSM Policy,Security group and deploy jenkins in it
Parameters:
  InstanceType:
    Description: WebServer EC2 instance type
    Type: String
    Default: t2.micro
  AmazonImageID:
    Description: The ID of the Amazon machine image (AMI)
    Type: String
    Default: 'ami-04db49c0fb2215364'
  JenkinsAutomationRole:
    Description: The ID of the Amazon machine image (AMI)
    Type: String
    Default: jenkinsservicerole

Resources:
  EC2Instance:
    DependsOn: InstanceSecurityGroup
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref InstanceType
      ImageId: !Ref AmazonImageID
      IamInstanceProfile: !Ref ManagedInstanceProfile
      Monitoring: true
      SecurityGroups: 
        - !Ref InstanceSecurityGroup
      BlockDeviceMappings:
        - DeviceName: /dev/sdc
          Ebs:
            SnapshotId: snap-0bdcc50b291983cea
            VolumeSize: 8
            VolumeType: io1
            Iops: 400
            DeleteOnTermination: true
      UserData:
        Fn::Base64:
          !Sub |
            #!/bin/bash -xe
            sudo su
            yum update -y
            yum install -y httpd
            yum install java -y
            wget -O /etc/yum.repos.d/jenkins.repo https://pkg.jenkins.io/redhat/jenkins.repo
            rpm --import https://pkg.jenkins.io/redhat/jenkins.io.key
            yum install jenkins -y
            service jenkins start 
            echo "Initial Admin Password: $(cat /var/lib/jenkins/secrets/initialAdminPassword)" > /var/www/html/index.html
            service httpd start
      Tags:
        - Key: team
          Value: dp
      
  InstanceSecurityGroup:
    DependsOn: Role
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable SSH access via port 
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 8080
          ToPort: 8080
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
          
  Role:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - ssm.amazonaws.com
            - ec2.amazonaws.com
          Action: sts:AssumeRole
      ManagedPolicyArns:
      - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
      Path: "/"
      RoleName: !Ref JenkinsAutomationRole
      
  ManagedInstanceProfile:
    DependsOn: Role
    Type: AWS::IAM::InstanceProfile
    Properties:
      Path: "/"
      Roles:
      - !Ref Role
      InstanceProfileName: !Ref JenkinsAutomationRole
          
      
